name: test_github_actions
on: [push]
jobs:
  check-bats-version:
    runs-on: windows-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
        with:
          submodules: true
      - name: setup python
        uses: actions/setup-python@v2
        with:
          python-version: 3.7
      - name: build
        run: ./build_mtree.bat
      - name: package addon
        run: python .github/scripts/setup_addon.py
      - name: upload zipped addon
        uses: actions/upload-artifact@v2
        with:
          name: blender addon
          path: tmp/*.zip
      
      - name: Create Release
        id: create_release
        uses: actions/create-release@latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release a${{ github.ref }}
          draft: true
          prerelease: true

