name: test_github_actions
on: [push]
jobs:
  build:
    strategy:
      matrix:
        include:
          - os: windows-latest
            extension: bat
            name: windows
          - os: ubuntu-latest
            extension: sh
            name: linux
    runs-on: ${{ matrix.os }}
    steps:
      - name: checkout
        uses: actions/checkout@v2
        with:
          submodules: true
      - name: setup python
        uses: actions/setup-python@v2
        with:
          python-version: 3.7
      - name: build
        run: ./build_mtree.${{ matrix.extension }}
      - name: package addon
        run: python .github/scripts/setup_addon.py
      - name: upload zipped addon
        uses: actions/upload-artifact@v2
        with:
          name: modular_tree_${{ matrix.name }}
          path: tmp/*.zip
  
  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download build artifacts
        uses: actions/download-artifact@v2
        with:
          path: ./build_artefacts
      - name: Update release
        uses: johnwbyrd/update-release@v1.0.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          draft: true
          files: ./build_artefacts/*.zip

